variable "rg_name" {}
variable "action_group_name" {}
variable "service_uri" {}
variable "metric_alert_name" {}
variable "webhook_receiver_name" {}
variable "db_metric_name" {}
variable "db_aggregation" {}
variable "db_operator" {}
variable "db_threshold" {}