variable "rg_name" {}
variable "action_group_name" {}
variable "service_uri" {}
variable "metric_alert_name" {}
variable "webhook_receiver_name" {}
variable "vm_metric_name" {}
variable "vm_aggregation" {}
variable "vm_operator" {}
variable "vm_threshold" {}