rg_name = "mkurra***"
action_group_name = "example-actiongroup"
webhook_service_uri = "http://example.com/alert"
webhook_receiver_name = "callmyapi"
vm_metric_alert_name = "vm-cpu-metric-alert"
vm_metric_name = "Percentage CPU"
vm_aggregation = "Average"
vm_operator = "GreaterThan"
vm_threshold = 90
